[package]

name = "syslog"
version = "4.0.1"
authors = [ "contact@geoffroycouprie.com" ]
description = "Send log messages to syslog"
license = "MIT"
repository = "https://github.com/Geal/rust-syslog"
documentation = "https://docs.rs/syslog"
keywords = ["syslog", "logs", "logging"]

[dependencies]
libc        = "^0.2"
time        = "^0.1"
log         = { version =  "^0.4", features = [ "std" ] }
error-chain = "^0.12"

[features]
nightly = []
